---
- name: DevOps Training
  hosts: testserver
  become: true
  become_user: root
  tasks:
    - name: Install Git
      package:
        name: git
        state: present
    - name: Install Docker
      package:
        name: docker.io
        state: present
    - name: Check whether we already have project repo
      stat:
        path: /home/ubuntu/devops-training
      register: p
    - name: Clone the application
      command: git clone https://github.com/ajit1411/devops-training.git
      when: p.stat.exists == False
    - name: Pull application updates
      shell: cd devops-training && git pull
      when: p.stat.exists == True
    - name: Build docker image
      shell: cd /home/ubuntu/devops-training && docker build -t my-devops-image-v1 . 
    - name: Run container
      command: docker run -itd -p 1411:80 --name my-devops-container my-devops-image-v1