---
- name: DevOps Training
  hosts: testserver
  become: true
  become_user: root
  tasks:
    - name: Install Git
      package: name=git state=present
    - name: Install Docker
      package: name=docker.io state=present
    - name: Get application update
      stat: /home/ubuntu/devops-training
      register: p
      when: p.stat.isdir
      command: git pull https://github.com/ajit1411/devops-training.git
    - name: Clone Application
      stat: /home/ubuntu/devops-training
      register: p
      when: not p.stat.isdir
      command: git pull https://github.com/ajit1411/devops-training.git
    - name: Build image
      command: docker build -t ajitjadhav1411/devops-training /home/ubuntu/devops-training/dockerfile
    - name: Deploy application
      command: docker run -itd -p 1411:80 --name test-devops ajitjadhav1411/devops-training:latest